# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create!(
name:"原口" ,
at_name: "as1111",
introduction: "こんにちは、",
profile_image: File.open("./app/assets/images/user1.jpg", ?r),
password: "123456",
email: "1@1"
)
User.create!(
name:"オーラス" ,
at_name: "gigabyte",
introduction: "こんばんは",
profile_image: File.open("./app/assets/images/user2.jpg", ?r),
password: "123456",
email: "2@2"
)
User.create!(
name:"エイスース" ,
at_name: "ROG",
introduction: "おはよう",
profile_image: File.open("./app/assets/images/user3.jpg", ?r),
password: "123456",
email: "3@3"
)
User.create!(
name:"エムエスアイ" ,
at_name: "msi",
introduction: "おはよう",
profile_image: File.open("./app/assets/images/user4.jpg", ?r),
password: "123456",
email: "4@4"
)
User.create!(
name:"MSI" ,
at_name: "miss1010",
introduction: "おはよう",
profile_image: File.open("./app/assets/images/user5.jpg", ?r),
password: "123456",
email: "5@5"
)
User.create!(
name:"清水" ,
at_name: "ocfire",
introduction: "おはよう",
profile_image: File.open("./app/assets/images/user6.jpg", ?r),
password: "123456",
email: "6@6"
)
User.create!(
name:"ギャラ兄さん" ,
at_name: "HOF",
introduction: "おはよう",
profile_image: File.open("./app/assets/images/user7.jpg", ?r),
password: "123456",
email: "7@7"
)
User.create!(
name:"アップル信者" ,
at_name: "imac",
introduction: "おはよう",
profile_image: File.open("./app/assets/images/user8.jpg", ?r),
password: "123456",
email: "8@8"
)
User.create!(
name:"ツクモ" ,
at_name: "tsukumo",
introduction: "おはよう",
profile_image: File.open("./app/assets/images/user9.jpg", ?r),
password: "123456",
email: "9@9"
)
Post.create!(
  [
    {
      user_id: "1",
      title: "低スペPCですが、、",
      cpu_name: "Xeon E3-1240v5",
      cooler_name: "CPU付属クーラー",
      motherboard_name: "GIGABYTE GA-X170-WS ECC (C236)G",
      memory_name: "Patriot PVE432G266C6KGY DDR4-2666 16GB x2",
      gpu_name: "ASRock Phantom Gaming X Radeon VII 16G",
      storage_name: "Phison PHM2-256GB (M.2 NVMe 256GB)",
      case_name: "InWin Alice",
      power_supply_name: "SilverStone SST-ET750-G 80+GOLD 750W",
      other: "無線LAN: ASUS PCE-AC68",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！
      					初心者です！初投稿となります！",
      value: "170000",
      tag_list: "Xeon,GIGABYTE,ASRock",
      post_image: File.open("./app/assets/images/pc1.jpg", ?r)
    },
    {
      user_id: "1",
      title: "core i9 10900で組んでみました！ ゲーミングPC",
      cpu_name: "Intel Core i9 10900",
      cooler_name: "Scythe Kotetsu Mk.II",
      motherboard_name: "ASUS ROG MAXIMUS XII APEX",
      memory_name: "Team x ASUS TUF Gaming Alliance 2x16GB",
      gpu_name: "ASUS ROG STRIX RTX2070SUPER(A8G)",
      storage_name: "Samsung 970 EVO+ 1TB",
      case_name: "InWin 928",
      power_supply_name: "ASUS ROG THOR 850",
      other: "S/B : Creative Sound Blaster Audigy FX",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！
      					メモリやストレージ関係は前回のを流用",
      value: "250000",
      tag_list: "corei9,ASUS,InWin",
      post_image: File.open("./app/assets/images/pc2.jpg", ?r)
    },
       {
      user_id: "1",
      title: "Ryzen PC",
      cpu_name: "AMD RYZEN9 3900X (12コア)",
      cooler_name: "ENERMAX LIQFUSION 240mm",
      motherboard_name: "ASUS ROG Strix X570-F Gaming",
      memory_name: "32GB G.Skill F4-3600C16 16GTZN",
      gpu_name: "Geforce GTX 1080Ti",
      storage_name: "Samsung 970 EVO+ 1TB",
      case_name: "NZXT H510 ELITE",
      power_supply_name: "ASUS ROG THOR 850",
      other: "S/B : Creative Sound Blaster Audigy FX",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！
      					ryzen9で作ってみました！",
      value: "240000",
      tag_list: "AMD,Ryzen9,NZXT",
      post_image: File.open("./app/assets/images/pc3.jpg", ?r)
    },
    {
      user_id: "2",
      title: "ゲーミングPC　ryzen5 3600",
      cpu_name: "AMD Ryzen5 3600",
      cooler_name: "NZXT Kraken Z63",
      motherboard_name: "B450 AORUS PRO Wi-Fi ATX",
      memory_name: "DDR4-3200 16GBx2",
      gpu_name: "PALIT RTX 2070 SUPER JS 8GB",
      storage_name: "WD SN500 500GB",
      case_name: "NZXT H510 Black",
      power_supply_name: "Apexgaming AG 750W",
      other: "Seagate Barracuda 3.5 4TB",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！
      					ryzen5 3600です。",
      value: "150000",
      tag_list: "AMD,NZXT,ゲーミングPC",
      post_image: File.open("./app/assets/images/pc4.jpg", ?r)
    },
    {
      user_id: "2",
      title: "10万円PC",
      cpu_name: "AMD Ryzen5 3500",
      cooler_name: "NZXT Kraken Z63",
      motherboard_name: "ASUS TUFGaming B450-PLUS",
      memory_name: "Patriot Viper Gaming DDR4(16GB)",
      gpu_name: "GeForce GTX1650",
      storage_name: "WD SN500 500GB",
      case_name: "LIANLI O11 RAZERcollab",
      power_supply_name: "玄人志向 500W電源",
      other: "Seagate Barracuda 3.5 4TB",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！
      					サブ機として使ってます。",
      value: "100000",
      tag_list: "AMD,NZXT,ゲーミングPC",
      post_image: File.open("./app/assets/images/pc5.jpg", ?r)
    },
    {
      user_id: "3",
      title: "15万円PC",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "Zen2に換装予定です！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/my-pc.jpg", ?r)
    },
    {
      user_id: "3",
      title: "20万円PC",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc6.jpg", ?r)
    },
    {

      user_id: "1",
      title: "25万円PC",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "250000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc7.jpg", ?r)
    },
    {
      user_id: "1",
      title: "30万円PC",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "300000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc8.jpg", ?r)
    },
    {
      user_id: "2",
      title: "ハイスペックPC",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "600000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc9.jpg", ?r)
    },
    {
      user_id: "6",
      title: "MicroATXで可愛いPC",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc10.jpg", ?r)
    },
    {
      user_id: "9",
      title: "ピカピカPC",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc11.jpg", ?r)
    },
    {
      user_id: "3",
      title: "MSIで構成しました",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc12.jpg", ?r)
    },
    {
      user_id: "7",
      title: "AORUS縛り！",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc22.jpg", ?r)
    },
    {
      user_id: "5",
      title: "本格水冷PC",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc20.jpg", ?r)
    },
    {
      user_id: "8",
      title: "簡易水冷にチャレンジ",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc15.jpg", ?r)
    },
    {
      user_id: "7",
      title: "ゲーミングPC",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc16.jpg", ?r)
    },
    {
      user_id: "6",
      title: "HOF! HOF! HOF!",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc17.jpg", ?r)
    },
    {
      user_id: "5",
      title: "Intel 信じtel",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc18.jpg", ?r)
    },
    {
      user_id: "9",
      title: "ゲーミングPC!",
      cpu_name: "AMD Ryzen5 2600",
      cooler_name: "付属クーラー",
      motherboard_name: "GIGABYTE X470 GAMING 7 WIFI",
      memory_name: "VENGEANCE RGB PRO 3000MHz 8GB×2",
      gpu_name: "ZOTAC RTX2060",
      storage_name: "crucial MX500",
      case_name: "thermaltake LEVEL 20MT ARGB",
      power_supply_name: "thermaltake 850W",
      other: "カービィ",
      pc_introduction: "*テストなので写真と金額は実際のものと異なります！",
      value: "150000",
      tag_list: "AMD,ゲーミングPC,AORUS,GIGABYTE",
      post_image: File.open("./app/assets/images/pc19.jpg", ?r)
    },
      ]
)